from ai.nn_helper import NUM_CARDS, NUM_ROUNDS, NUM_STACK_CARDS


NUM_SITTING_ORDER = NUM_STACK_CARDS
NUM_ENCODED_STACK = NUM_STACK_CARDS + NUM_CARDS * 2
NUM_ENCODED_PREVIOUS_STACKS = NUM_ENCODED_STACK * (NUM_ROUNDS - 1)
NUM_ENCODED_HAND_CARDS = NUM_CARDS

INPUT_SIZE = (
    NUM_SITTING_ORDER
    + NUM_ENCODED_STACK
    + NUM_ENCODED_PREVIOUS_STACKS
    + NUM_ENCODED_HAND_CARDS
)
OUTPUT_SIZE = 32

class Encoding:
    NOT_PLAYED = 0
    PLAYED = 1
    ENEMY = 1
    ALLY = 2
    US = 3